name: test
on: [push, pull_request]

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        nim-version: ["2.0.0", "stable"]
    name: test (Nim ${{ matrix.nim-version }})
    steps:
      - uses: actions/checkout@v4
      - uses: jiro4989/setup-nim-action@v1
        with:
          nim-version: ${{ matrix.nim-version }}

      - name: Prime Nimble index
        run: nimble refresh -y

      - name: Build & Test
        run: nimble test -y
